export enum Subjects {
  UserCreated = 'user:created',
  UserUpdated = 'user:updated',
  UserAddressCreated = 'user_address:created',
  UserAddressUpdated = 'user_address:updated',
  UserAddressDeleted = 'user_address:deleted',
  EmailSending = 'email:sending',
  RestaurantCategoryDeleted = 'restaurant_category:deleted',
  RestaurantCreated = 'restaurant:created',
  RestaurantUpdated = 'restaurant:updated',
  RestaurantDeleted = 'restaurant:deleted',
  IngredientCreated = 'ingredient:created',
  IngredientUpdated = 'ingredient:updated',
  IngredientDeleted = 'ingredient:deleted',
  MenuItemCreated = 'menu:created',
  MenuItemUpdated = 'menu:updated',
  MenuItemDeleted = 'menu:deleted',
  OrderCreated = 'order:created',
  OrderUpdated = 'order:updated',
}
